# Generated by Django 4.0 on 2021-12-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address_street', models.CharField(max_length=50)),
                ('adress_number', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('postcode', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
