# Generated by Django 4.0 on 2021-12-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='username',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
