# Generated by Django 3.2.9 on 2021-12-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona_app', '0002_persona_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='picture',
            field=models.CharField(max_length=60),
        ),
    ]
