# Generated by Django 4.0 on 2021-12-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona_app', '0003_alter_persona_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='adress_number',
            new_name='address_number',
        ),
    ]
